### PR TITLE
Adds support for job files endpoints.

### PR DESCRIPTION
**Pull request by qubyte**

### CODE REVIEW

**Comment by inca** [comment]
Pitching it: the protocol around file downloads was designed in a way that doesn't expose any ids or other opaque details about them. Client should be able to simply download the file using an URL. Any dependency on Client knowing the structure of the URL or some other means of retrieving the `fileId` will result in a sneaky undocumented dependency.

**Comment by qubyte** [comment]
I think I've missed something here. Where will the file URLs be coming from?

**Comment by inca** [comment]
https://protocol.automationcloud.net/Generic#File

We need to be able to switch to a different file hosting backend if necessary, so Clients should not depend on this URL containing `fileId` — nor that this URL should even belong to `automationcloud.net`.

For this exact reason, making this request authenticated was also a bad idea (and is still a big security risk) — but unfortunately this ship has long sailed.

**Comment by inca** [comment]
That being said, if the requirements have changed, we can (and probably should) redesign this. The changes will affect protocol, script and clients though.

**Comment by qubyte** [comment]
As things are implemented, there's no obvious security risk. We'd always need to provide a service to front the real storage service (which is all upload-download is anyway).

**Comment by qubyte** [comment]
Perhaps this points to the need for the JS-SDK to be able to perform uploads.

**Comment by qubyte** [comment]
If there are no objections, I'll merge this.

**Pull request merged**
